<?php

$title = 'Edit Driver';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
 $form->setAttribute('action', $this->url('driver', array('action' => 'edit')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('fullName'));
 echo $this->formRow($form->get('DoB'));
 echo $this->formRow($form->get('DoD'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();