<?php

$title = 'Edit Country';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<form method="post">
  code: <input type="text" name="code" value="<?php echo $country->getCode(); ?>"><br>
  name: <input type="text" name="name" value="<?php echo $country->getName(); ?>"><br>
  nationality: <input type="text" name="nationality" value="<?php echo $country->getNationality(); ?>"><br>
  <input type="submit" value="Submit">
</form>

