<h1>Driver Base</h1>
<p>Development of a new driver database. Designed from scratch to use latest Web 2.0 standards, this new
web application should be able to combine all the different series' data into one coherent data set.<p>


<p>The driverbase can contain the following data types:</p>
<ul>
<li><a href="<?php echo $this->url('driverbase', array('action'=>'listDrivers'));?>">Drivers</a></li>
<li><a href="<?php echo $this->url('driverbase', array('action'=>'listTeams'));?>">Teams</a></li>
<li>Manufacturer</li>
<li>Car</li>
<li>Series</li>
<li>Title</li>
<li>Calendar</li>
</ul>

<ul>
<li><a href="<?php echo $this->url('driverbase', array('action'=>'listCountries'));?>">Countries</a></li>
<li><a href="<?php echo $this->url('driverbase', array('action'=>'listCircuits'));?>">Circuits</a></li>
</ul>

<p>You will need to <a href='/user/login'>login</a> to maintain the data</p>
