<div>
    <div>
        <div>
            <div>
                <h3>Drivers</h3>
            </div>
            <div>
                <a href="<?php echo $this->url('driverbase', array('action'=>'addDriver'));?>">Add Driver</a>

                <?php if (isset($drivers)) : ?>
                <table>
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Full name</th>
                        <th></th>
                    </tr>
                    </thead>
                <?php foreach($drivers as $driver): ?>
                    <tbody>
                    <tr>
                        <td><?php echo $driver->getId(); ?></td>
                        <td><?php echo $driver->getFullName(); ?></td>
                        <td>
                            <a href="<?php echo $this->url('driverbase', array('action'=>'displayDriver', 'id' => $driver->getId()));?>">Display</a> |
                            <a href="<?php echo $this->url('driverbase', array('action'=>'editDriver', 'id' => $driver->getId()));?>">Edit</a> |
                            <a href="<?php echo $this->url('driverbase', array('action'=>'deleteDriver', 'id' => $driver->getId()));?>">Delete</a>
                        </td>
                    </tr>
                    </tbody>
                <?php endforeach; ?>
                </table>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>