<div>
    <div>
        <div>
            <div>
                <h3>Countries</h3>
            </div>
            <div>
                <a href="<?php echo $this->url('driverbase', array('action'=>'addCountry'));?>">Add Country</a>

                <?php if (isset($countries)) : ?>
                <table>
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Code</th>
                        <th>Name</th>
                        <th>Nationality</th>
                        <th></th>
                    </tr>
                    </thead>
                <?php foreach($countries as $country): ?>
                    <tbody>
                    <tr>
                        <td><?php echo $country->getId(); ?></td>
                        <td><?php echo $country->getCode(); ?></td>
                        <td><?php echo $country->getName(); ?></td>
                        <td><?php echo $country->getNationality(); ?></td>
                        <td>
                            <a href="<?php echo $this->url('driverbase', array('action'=>'displayCountry', 'id' => $country->getId()));?>">Display</a> |
                            <a href="<?php echo $this->url('driverbase', array('action'=>'editCountry', 'id' => $country->getId()));?>">Edit</a> |
                            <a href="<?php echo $this->url('driverbase', array('action'=>'deleteCountry', 'id' => $country->getId()));?>">Delete</a>
                        </td>
                    </tr>
                    </tbody>
                <?php endforeach; ?>
                </table>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>