<?php
$form = $this->form;
$form->setAttribute('action',
	$this->url('application', array('controller' => 'index', 'action' => 'add')));

//$form->setAttribute('action', $this->url('driver', array('action' => 'edit')));

$form->prepare();

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();

$this->inlineScript()->offsetSetScript(99,"
$(function() {
   $('input#start').datepicker({
       dateFormat: 'yy-mm-dd',
       showOtherMonths: true,
       selectOtherMonths: true,
   });
});
");